name: QTC CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  BUILD_TYPE: Release
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libssl-dev libboost-all-dev
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      - name: Build
        run: cmake --build build --parallel
      - name: Test binary
        run: ./build/qtc_node --version || true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qtc-linux-${{ github.sha }}
          path: build/qtc_node
